# docker-compose.yml
version: '3.8'

services:
  redis:
    image: redis:latest
    command: redis-server
    ports:
      - 6379:6379
  app:
    image: nestjs-chat-sample
    ports:
      - 3000:3000
    links:
      - redis
    environment: 
      - REDIS_HOST=redis
